apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-wb-service-account
  namespace: ai-website-builder
  labels:
    app: ai-website-builder
  annotations:
    # This will be updated by eksctl when creating IRSA
    # eks.amazonaws.com/role-arn: arn:aws:iam::959545103699:role/ai-wb-app-role
